// <auto-generated>
// 由 tools/assets/generate.mjs 依据 example/assets 磁盘实测字节生成，不要手改。
// 重新生成：node tools/assets/generate.mjs
// </auto-generated>

using System.Collections.Generic;

namespace Aura3D.Examples.Assets;

public static partial class AssetManifest
{
    /// <summary>
    /// 全部已登记资产。顺序即功能页资产列表的展示顺序。
    /// </summary>
    public static IReadOnlyList<AssetRef> All { get; } =
    [
        // —— 仅桌面资产：Assimp 原生库读的 FBX ——
        new("FbxMannequin", "models/fbx/SK_Mannequin.FBX", 941_472, WebFriendly: false),
        new("FbxIdle", "models/fbx/Idle_Rifle_Hip.FBX", 1_290_352, WebFriendly: false),
        new("FbxJogFwd", "models/fbx/Jog_Fwd_Rifle.FBX", 697_072, WebFriendly: false),

        // —— 模型 ——
        new("LionHead", "models/lion_head_1k.glb", 1_664_712),
        new("CoffeeTable", "models/coffee_table_round_01_1k.glb", 443_568),
        new("Stool", "models/wooden_stool_02_1k.glb", 913_720),
        new("Lightbulb", "models/lightbulb_01_1k.glb", 1_263_780),
        new("Stones", "models/stones_01.glb", 823_932),
        new("Present", "models/present_11.glb", 2_812_632),
        new("Soldier", "models/Soldier.glb", 1_169_684),
        new("CelCharacter", "models/NPC_Avatar_Girl_Sword_Nilou.glb", 9_206_952),

        // —— 贴图 ——
        new("BackgroundJpg", "textures/background-1024.jpg", 138_328),
        new("ParticleFirePng", "textures/fire-512.png", 499_431),

        // —— 环境：HDRI 与立方图六面 ——
        new("SkyboxPx", "textures/skybox/px.jpg", 54_148),
        new("SkyboxNx", "textures/skybox/nx.jpg", 52_031),
        new("SkyboxPy", "textures/skybox/py.jpg", 23_384),
        new("SkyboxNy", "textures/skybox/ny.jpg", 77_041),
        new("SkyboxPz", "textures/skybox/pz.jpg", 54_143),
        new("SkyboxNz", "textures/skybox/nz.jpg", 46_765),
        new("Hdr1k", "environments/buikslotermeerplein_1k.hdr", 1_624_392),
    ];
}
