//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aura3D.Core {
    using System;
    
    
    /// <summary>
    /// Represents the shader resource type.
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShaderResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShaderResource() {
        }
        
        /// <summary>
        /// Gets the resource manager.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aura3D.Core.ShaderResource", typeof(ShaderResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        /// Gets the culture.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Gets the background frag.
        /// </summary>
        public static string BackgroundFrag {
            get {
                return ResourceManager.GetString("BackgroundFrag", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the background vert.
        /// </summary>
        public static string BackgroundVert {
            get {
                return ResourceManager.GetString("BackgroundVert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the debug frag.
        /// </summary>
        public static string DebugFrag {
            get {
                return ResourceManager.GetString("DebugFrag", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the debug vert.
        /// </summary>
        public static string DebugVert {
            get {
                return ResourceManager.GetString("DebugVert", resourceCulture);
            }
        }

        /// <summary>
        /// Gets the mesh frag.
        /// </summary>
        public static string MeshFrag {
            get {
                return ResourceManager.GetString("MeshFrag", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the mesh vert.
        /// </summary>
        public static string MeshVert {
            get {
                return ResourceManager.GetString("MeshVert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the no light frag.
        /// </summary>
        public static string NoLightFrag {
            get {
                return ResourceManager.GetString("NoLightFrag", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the no light vert.
        /// </summary>
        public static string NoLightVert {
            get {
                return ResourceManager.GetString("NoLightVert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the shadow map frag.
        /// </summary>
        public static string ShadowMapFrag {
            get {
                return ResourceManager.GetString("ShadowMapFrag", resourceCulture);
            }
        }
        
        /// <summary>
        /// Gets the shadow map vert.
        /// </summary>
        public static string ShadowMapVert {
            get {
                return ResourceManager.GetString("ShadowMapVert", resourceCulture);
            }
        }
    }
}
